version: '3.8'
services:
  server:
    container_name: Server
    build: ./server/
    ports: 
      - 8080:8080
    networks:
      - cs50_final_network
    environment:
      IN_DOCKER: 'true'
      DB_HOST: database
      DB_PORT: 3306
      # From .env file
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      CERT_PATH: ${CERT_PATH}
      KEY_PATH: ${KEY_PATH}

    volumes:
      - './docker-volume/server:/server-data'
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: Database
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_NAME}   
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      # Yes this is not best practice 🤷‍♀️ but it is a personal project only
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './docker-volume/.mysql-data/${DB_NAME}:/var/lib/mysql'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - cs50_final_network

volumes:
  db_data:
    driver: local

networks:
  cs50_final_network:
      driver: bridge
      name: cs50_final_network
