version: '3.8'
services:
  server:
    container_name: Server
    build: ./server/
    ports: 
      - 8080:8080
    networks:
      - db_network
    environment:
      DB_USER: root
      DB_PASS: password
      DB_NAME: dashboard
      DB_HOST: database
      DB_PORT: 3306

  database:
    image: mysql:5.7
    container_name: Database
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'dashboard'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/dashboard:/var/lib/mysql'
    networks:
      - db_network

volumes:
  db_data:
    driver: local

networks:
  db_network:
      driver: bridge
      name: db_network
