version: '3.8'
services:
  server:
    container_name: Whiteboard-Server
    build: ./server/
    ports: 
      - 8080:8080

  database:
    image: mysql:5.7
    container_name: Whiteboard-Database
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'Whiteboard'   
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/Whiteboard:/var/lib/mysql'

volumes:
  db_data:
    driver: local

networks:
  db_network:
