FROM python:3.9-slim-buster

# Install system-level dependencies for MySQL client
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Setup project
WORKDIR /app
COPY ./server/requirements.txt /app
RUN pip install -r requirements.txt

# Copy project files
RUN mkdir -p /server-data/static
COPY ./../static/DEFAULT.png /app/static/DEFAULT.png
COPY ./server .

# Run the application
EXPOSE 5000
ENV FLASK_APP=app.py

CMD ["python","src/app.py"]